version: '3'
services:
  frontend: 
    image: sedadede9650/fe:proje
    ports:
      - "3000:3000"
    networks:
      - react-express
    depends_on:
      - backend
  backend:
    image: sedadede9650/be:proje
    build:
      context: backend
    expose:
      - 3000
    networks:
      - express-mongo
      - react-express
    depends_on:
      - mongo
  mongo:
    restart: always
    image: sedadede9650/db:proje
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo: