name: Docker Images Build&Push

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        logout: false
          
    - name: Build Backend Docker Image
      run: docker build -t sedadede9650/be:proje ./react-express-mongodb/backend

    - name: Push Backend Docker Image to Docker Hub
      run: docker push sedadede9650/be:proje
      
    - name: Build Frontend Docker Image
      run: docker build -t sedadede9650/fe:proje ./react-express-mongodb/frontend

    - name: Push Frontend Docker Image to Docker Hub
      run: docker push sedadede9650/fe:proje

    - name: Build DB Docker Image
      run: docker build -t sedadede9650/db:proje -f react-express-mongodb/dockerfile.db ./react-express-mongodb

    - name: Push DB Docker Image to Docker Hub
      run: docker push sedadede9650/db:proje
